### ISSUE TITLE
Can't find the file '/iarai/home/yonghao.xu/PreTrainedModel/fcn8s_from_caffe.pth'

### ISSUE THREAD

**Issue by xxxolllllllll** [YonghaoXu/UAE-RS#5]
Hi,
How to get the file?

**Comment by xxxolllllllll** [comment]
when i excute the script----"CUDA_VISIBLE_DEVICES=1 python pretrain_seg.py --model 'fcn8s' --dataID 1 --root_dir /home/zgt/projects/rs/UAE-RS-main/datasets/" in my bash,it tells me '' CUDA_VISIBLE_DEVICES=1 python pretrain_seg.py --model 'fcn8s' --dataID 1 --root_dir /home/zgt/projects/rs/UAE-RS-main/datasets/
/home/zgt/projects/rs/UAE-RS-main/segmentation/pretrain_seg.py:22: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  name_classes = np.array(['impervious surfaces','buildings','low vegetation','trees','cars'], dtype=np.str)
Traceback (most recent call last):
  File "/home/zgt/projects/rs/UAE-RS-main/segmentation/pretrain_seg.py", line 259, in <module>
    main(parser.parse_args())
  File "/home/zgt/projects/rs/UAE-RS-main/segmentation/pretrain_seg.py", line 66, in main
    saved_state_dict = torch.load(args.restore_from)
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/iarai/home/yonghao.xu/PreTrainedModel/fcn8s_from_caffe.pth'
''

**Comment by YonghaoXu** [comment]
Hi, you can download this model [here](https://drive.google.com/file/d/1PGuOb-ZIOc10aMGOxj5xFSubi8mkVXaq/view?usp=sharing).
