### ISSUE TITLE
top_mosaic_09cm_area37.png can not be found in Vaihingen/gt/ directory

### ISSUE THREAD

**Issue by xxxolllllllll** [YonghaoXu/UAE-RS#6]
mask_top_mosaic_09cm_area11.tif  mask_top_mosaic_09cm_area15.tif  mask_top_mosaic_09cm_area28.tif  ,only these file could be found.
the other file could be found in Vaihingen/img/.
when I run 'CUDA_VISIBLE_DEVICES=3 python pretrain_seg.py --model 'fcn8s' --dataID 1 --root_dir /home/zgt/projects/rs/UAE-RS-main/datasets/' in my bash, it tells me
 '''
/home/zgt/projects/rs/UAE-RS-main/segmentation/pretrain_seg.py:22: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  name_classes = np.array(['impervious surfaces','buildings','low vegetation','trees','cars'], dtype=np.str)
Traceback (most recent call last):
  File "/home/zgt/projects/rs/UAE-RS-main/segmentation/pretrain_seg.py", line 259, in <module>
    main(parser.parse_args())
  File "/home/zgt/projects/rs/UAE-RS-main/segmentation/pretrain_seg.py", line 127, in main
    for batch_index, src_data in enumerate(src_loader):
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zgt/projects/rs/UAE-RS-main/segmentation/dataset/seg_dataset.py", line 63, in __getitem__
    label = Image.open(datafiles["label"])
  File "/home/zgt/anaconda3/envs/env_1/lib/python3.9/site-packages/PIL/Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
**_FileNotFoundError: [Errno 2] No such file or directory: '/home/zgt/projects/rs/UAE-RS-main/datasets/Vaihingen/gt/top_mosaic_09cm_area37.png'**_
'''

**Comment by xxxolllllllll** [comment]
Should I move the files under /home/zgt/projects/rs/UAE-RS-main/datasets/Vaihingen/img/ to /home/zgt/projects/rs/UAE-RS-main/datasets/Vaihingen/gt/? If I do this, Have some effects?

**Comment by YonghaoXu** [comment]
Hi, please convert the annotation files into the `.png` format by yourself, where the pixel values range from 0 to num_classes-1.
